import re
import json
import base64
import hashlib
from urllib.parse import urlparse, parse_qs
import requests
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend
import logger
from utils import DEFAULT_HEADERS


def _evp_bytes_to_key(password: bytes, salt: bytes, key_len: int = 32, iv_len: int = 16) -> tuple[bytes, bytes]:
    """OpenSSL EVP_BytesToKey key derivation matching CryptoJS default AES encryption."""
    d = b''
    d_i = b''
    while len(d) < key_len + iv_len:
        d_i = hashlib.md5(d_i + password + salt).digest()
        d += d_i
    return d[:key_len], d[key_len:key_len + iv_len]


def _cryptojs_aes_decrypt(ciphertext_b64: str, passphrase: str) -> str:
    """Decrypts OpenSSL-compatible AES-256-CBC ciphertext generated by CryptoJS."""
    raw = base64.b64decode(ciphertext_b64)
    if not raw.startswith(b'Salted__'):
        raise ValueError("Invalid CryptoJS ciphertext header (missing Salted__).")
    salt = raw[8:16]
    encrypted = raw[16:]
    key, iv = _evp_bytes_to_key(passphrase.encode("utf-8"), salt, 32, 16)
    cipher = Cipher(algorithms.AES(key), modes.CBC(iv), backend=default_backend())
    decryptor = cipher.decryptor()
    padded_data = decryptor.update(encrypted) + decryptor.finalize()
    unpadder = padding.PKCS7(128).unpadder()
    data = unpadder.update(padded_data) + unpadder.finalize()
    return data.decode("utf-8")


def _extract_stream_from_decrypted(decrypted: str, target_id: str | None) -> dict | None:
    """
    Parses a Shaka MPD manifest URL and ClearKey pairs (k1:k2) from decrypted Blogma JS.
    Handles three cases: targeted channel block, multi-channel canais object, single manifest.
    """
    # Case 1: Named channel block — e.g. "ds": { url: "...", k1: "...", k2: "..." }
    if target_id:
        pattern = rf'[\'"]?{re.escape(target_id)}[\'"]?\s*:\s*\{{([^}}]+)\}}'
        m_target = re.search(pattern, decrypted)
        if m_target:
            block = m_target.group(1)
            m_url = re.search(r'(?:url|manifest|file|source|manifestUri)\s*:\s*[\'"]([^\'"]+)[\'"]', block)
            if m_url:
                result = _build_stream_result(m_url.group(1), block)
                if result:
                    return result

    # Case 2: canais/channels/streams dictionary with named entries
    canais_match = re.search(r'(?:canais|channels|streams)\s*=\s*(\{[\s\S]*?\n\s*\};)', decrypted)
    if canais_match and target_id:
        raw_canais = canais_match.group(1)
        for cm in re.finditer(
            r'[\'"]?([a-zA-Z0-9_-]+)[\'"]?\s*:\s*\{\s*(?:url|manifest|file)\s*:\s*[\'"]([^\'"]+)[\'"][\s\S]*?\}',
            raw_canais
        ):
            if cm.group(1) == target_id:
                block = cm.group(0)
                m_url = re.search(r'(?:url|manifest|file)\s*:\s*[\'"]([^\'"]+)[\'"]', block)
                if m_url:
                    result = _build_stream_result(m_url.group(1), block)
                    if result:
                        return result

    # Case 3: Single manifest definition anywhere in the decrypted JS
    m_manifest = re.search(
        r'(?:manifestUri|manifest|file|source|url)\s*[:=]\s*[\'"]([^\'"]+\.(?:mpd|m3u8)[^\'"]*)[\'"]',
        decrypted
    )
    if m_manifest:
        return _build_stream_result(m_manifest.group(1), decrypted)

    return None


def _build_stream_result(raw_url: str, context: str) -> dict | None:
    """Normalises a manifest URL and extracts ClearKey pairs from the surrounding context."""
    manifest_url = raw_url.strip()
    if manifest_url.startswith("//"):
        manifest_url = "https:" + manifest_url

    if manifest_url.endswith(".m3u8") or ".m3u8?" in manifest_url:
        return {"type": "hls", "url": manifest_url}

    # Try explicit k1/k2 fields first, then fall back to generic hex-pair scan
    m_k1 = re.search(r'k1\s*[:=]\s*[\'"]([a-fA-F0-9]+)[\'"]', context)
    m_k2 = re.search(r'k2\s*[:=]\s*[\'"]([a-fA-F0-9]+)[\'"]', context)
    if m_k1 and m_k2:
        return {"type": "shaka", "manifest": manifest_url, "keys": {m_k1.group(1): m_k2.group(1)}}

    keys = {}
    for km in re.finditer(r'[\'"]([a-fA-F0-9]{16,32})[\'"]\s*:\s*[\'"]([a-fA-F0-9]{16,32})[\'"]', context):
        keys[km.group(1)] = km.group(2)

    return {"type": "shaka", "manifest": manifest_url, "keys": keys}


def resolve_blogma_stream(url: str, proxies: dict = None) -> dict | None:
    """
    Decrypts a Blogma helper page (sewzzy, swxzyy, nazity, kkzawe, etc.) to extract
    the native Shaka DASH manifest and ClearKey pairs, bypassing browser anti-embed checks.
    Returns a stream dict with type 'shaka' or 'hls', or None if decryption fails.
    """
    headers = {**DEFAULT_HEADERS, "Referer": "https://m.blogma.sbs/"}
    try:
        resp = requests.get(url, headers=headers, timeout=10, proxies=proxies)
        if resp.status_code != 200 or "__payload" not in resp.text:
            return None

        m_payload = re.search(r'var\s+__payload\s*=\s*\"([^\"]+)\"', resp.text)
        m_ka = re.search(r'var\s+__ka\s*=\s*(\[[^\]]+\])', resp.text)
        m_kb = re.search(r'var\s+__kb\s*=\s*(\[[^\]]+\])', resp.text)
        m_ma = re.search(r'var\s+__ma\s*=\s*(\d+)', resp.text)
        m_mb = re.search(r'var\s+__mb\s*=\s*(\d+)', resp.text)

        if not (m_payload and m_ka and m_kb and m_ma and m_mb):
            return None

        payload = m_payload.group(1)
        ka = json.loads(m_ka.group(1))
        kb = json.loads(m_kb.group(1))
        ma = int(m_ma.group(1))
        mb = int(m_mb.group(1))

        # Reconstruct obfuscated passphrases via bitwise XOR with mask integers
        kA = ''.join([chr(int(x, 16) ^ ma) for x in ka])
        kB = ''.join([chr(int(x, 16) ^ mb) for x in kb])

        decB = _cryptojs_aes_decrypt(payload, kB)
        decA = _cryptojs_aes_decrypt(decB, kA)

        parsed_url = urlparse(url)
        qs = parse_qs(parsed_url.query)
        target_id = qs.get("id", [None])[0] or qs.get("src", [None])[0]

        return _extract_stream_from_decrypted(decA, target_id)

    except Exception as e:
        logger.warning(f"Plugin (footyy/decryptor): Failed to decrypt Blogma DRM stream from '{url}': {e}")

    return None
